import { User } from '../types/user';

// Helper function to generate random boolean
const getRandomPresence = (): boolean => Math.random() < 0.5;

// Original user data with randomized presence
export const userData: User[] = [
  { id: 1, name: 'Alice', isPresent: getRandomPresence() },
  { id: 2, name: 'Bob', isPresent: getRandomPresence() },
  { id: 3, name: 'Charlie', isPresent: getRandomPresence() },
  { id: 4, name: 'David', isPresent: getRandomPresence() },
  { id: 5, name: 'Eve', isPresent: getRandomPresence() },
  { id: 6, name: 'Frank', isPresent: getRandomPresence() },
  { id: 7, name: 'Grace', isPresent: getRandomPresence() },
  { id: 8, name: 'Hank', isPresent: getRandomPresence() },
  { id: 9, name: 'Ivy', isPresent: getRandomPresence() },
  { id: 10, name: 'Jack', isPresent: getRandomPresence() },
  { id: 11, name: 'Kathy', isPresent: getRandomPresence() },
  { id: 12, name: 'Leo', isPresent: getRandomPresence() },
  { id: 13, name: 'Mona', isPresent: getRandomPresence() },
  { id: 14, name: 'Nina', isPresent: getRandomPresence() },
  { id: 15, name: 'Oscar', isPresent: getRandomPresence() },
  { id: 16, name: 'Paul', isPresent: getRandomPresence() },
  { id: 17, name: 'Quincy', isPresent: getRandomPresence() },
  { id: 18, name: 'Rachel', isPresent: getRandomPresence() },
  { id: 19, name: 'Steve', isPresent: getRandomPresence() },
  { id: 20, name: 'Tina', isPresent: getRandomPresence() },
  { id: 21, name: 'Uma', isPresent: getRandomPresence() },
  { id: 22, name: 'Vince', isPresent: getRandomPresence() },
  { id: 23, name: 'Wendy', isPresent: getRandomPresence() },
  { id: 24, name: 'Xander', isPresent: getRandomPresence() },
  { id: 25, name: 'Yara', isPresent: getRandomPresence() },
  { id: 26, name: 'Zane', isPresent: getRandomPresence() },
  { id: 27, name: 'Amy', isPresent: getRandomPresence() },
  { id: 28, name: 'Brian', isPresent: getRandomPresence() },
  { id: 29, name: 'Cathy', isPresent: getRandomPresence() },
  { id: 30, name: 'Derek', isPresent: getRandomPresence() },
  { id: 31, name: 'Ella', isPresent: getRandomPresence() },
  { id: 32, name: 'Fred', isPresent: getRandomPresence() },
  { id: 33, name: 'Gina', isPresent: getRandomPresence() },
  { id: 34, name: 'Harry', isPresent: getRandomPresence() },
  { id: 35, name: 'Iris', isPresent: getRandomPresence() },
  { id: 36, name: 'Jake', isPresent: getRandomPresence() },
  { id: 37, name: 'Kara', isPresent: getRandomPresence() },
  { id: 38, name: 'Liam', isPresent: getRandomPresence() },
  { id: 39, name: 'Mia', isPresent: getRandomPresence() },
  { id: 40, name: 'Noah', isPresent: getRandomPresence() },
  { id: 41, name: 'Olivia', isPresent: getRandomPresence() },
  { id: 42, name: 'Pete', isPresent: getRandomPresence() },
  { id: 43, name: 'Quinn', isPresent: getRandomPresence() },
  { id: 44, name: 'Rita', isPresent: getRandomPresence() },
  { id: 45, name: 'Sam', isPresent: getRandomPresence() },
  { id: 46, name: 'Tara', isPresent: getRandomPresence() },
  { id: 47, name: 'Ursula', isPresent: getRandomPresence() },
  { id: 48, name: 'Victor', isPresent: getRandomPresence() },
  { id: 49, name: 'Walt', isPresent: getRandomPresence() },
  { id: 50, name: 'Xena', isPresent: getRandomPresence() },
  { id: 51, name: 'Yvonne', isPresent: getRandomPresence() },
  { id: 52, name: 'Zack', isPresent: getRandomPresence() },
];
